spring:
  application:
    name: bank-service

  datasource:
    url: jdbc:mysql://localhost:3306/bank_service_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081

bank:
  aa-api-key: ${AA_API_KEY}