spring:
  application:
    name: bank-service

  datasource:
    url: jdbc:mysql://localhost:3306/consentchain_auth
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081


bank:
  aa-api-key: AA-SECRET-123