spring:
  application:
    name: aggregator-service

  datasource:
    url: jdbc:mysql://localhost:3306/aggregator_service_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

fip:
  base-url: http://localhost:8081
  aa-api-key: AA-SECRET-123